[build]
  publish = "public"
  functions = "netlify/functions"
  command = ""

[functions]
  directory = "netlify/functions"

[functions."verify"]
  included_files = ["netlify/functions/codes.json"]

[dev]
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Catch-all for product code paths to SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 