[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# QR legacy path
[[redirects]]
  from = "/GS26/QR"
  to = "/.netlify/functions/qr"
  status = 302

# Catch-all for product code paths to SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 